import { defineType, defineField } from 'sanity';

export const door3DModelSchema = defineType({
  name: 'door3DModel',
  title: 'Modèles 3D portes (GLB)',
  type: 'document',
  groups: [
    { name: 'main', title: 'Principal' },
    { name: 'meshes', title: 'Mesh names (Three.js)' },
    { name: 'transform', title: 'Transformation' },
  ],
  fields: [
    defineField({
      name: 'name',
      title: 'Nom interne',
      type: 'string',
      group: 'main',
      description: "Ex: 'Porte lisse générique', 'Porte vitrage asymétrique'",
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug technique',
      type: 'slug',
      group: 'main',
      description: "Ex: door-flat, door-glazed, door-paneled — sert au lookup côté code.",
      options: { source: 'name', maxLength: 60 },
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'glbFile',
      title: 'Fichier GLB',
      type: 'file',
      group: 'main',
      description: 'Upload du modèle 3D (.glb). Format glTF 2.0 binaire.',
      options: { accept: '.glb,.gltf' },
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'thumbnail',
      title: 'Aperçu (image)',
      type: 'image',
      group: 'main',
      description: 'Capture du rendu — affichée dans Sanity et comme poster.',
    }),
    defineField({
      name: 'applicableDoors',
      title: 'Portes couvertes par ce modèle',
      type: 'array',
      group: 'main',
      of: [{ type: 'reference', to: [{ type: 'door' }] }],
      description: 'Sélectionne les portes du catalogue auxquelles ce modèle 3D s\'applique. Une seule porte 3D peut couvrir plusieurs entrées du catalogue.',
    }),
    defineField({
      name: 'availableFinitions',
      title: 'Finitions disponibles pour ce modèle',
      type: 'array',
      group: 'main',
      of: [{ type: 'reference', to: [{ type: 'finition' }] }],
      description:
        'Les couleurs et textures que le client peut sélectionner pour ce modèle dans le configurateur. Réfère des documents "Finition".',
    }),
    defineField({
      name: 'panelMeshName',
      title: 'Nom du mesh "panneau"',
      type: 'string',
      group: 'meshes',
      description: 'Nom du mesh principal sur lequel appliquer la finition (couleur/texture). Par défaut "Mesh1" pour les GLB Meshy.',
      initialValue: 'Mesh1',
    }),
    defineField({
      name: 'handleAttachMeshName',
      title: 'Nom du mesh "poignée" (à remplacer)',
      type: 'string',
      group: 'meshes',
      description: 'Si la poignée est un sub-mesh nommé, code la masque pour la remplacer par la poignée Sanity sélectionnée.',
    }),
    defineField({
      name: 'handleAttachX',
      title: 'Point d\'attache poignée — X',
      type: 'number',
      group: 'transform',
      description: 'Position relative (-0.5 à 0.5) où ancrer le mesh poignée externe.',
      initialValue: 0.35,
    }),
    defineField({
      name: 'handleAttachY',
      title: 'Point d\'attache poignée — Y',
      type: 'number',
      group: 'transform',
      description: 'Hauteur (0 = bas, 1 = haut). Standard ~0.45 (à hauteur de main).',
      initialValue: 0.45,
    }),
    defineField({
      name: 'scale',
      title: 'Échelle du modèle',
      type: 'number',
      group: 'transform',
      description: 'Multiplicateur si le GLB est mal dimensionné. Laisse 1 par défaut.',
      initialValue: 1,
    }),
    defineField({
      name: 'published',
      title: 'Publié',
      type: 'boolean',
      group: 'main',
      initialValue: true,
    }),
  ],
  preview: {
    select: { title: 'name', subtitle: 'slug.current', media: 'thumbnail' },
  },
});
