import { defineType, defineField } from 'sanity';

export const finitionSchema = defineType({
  name: 'finition',
  title: 'Finitions (couleurs/textures portes 3D)',
  type: 'document',
  groups: [
    { name: 'main', title: 'Principal' },
    { name: 'pbr', title: 'Aspect matériau (PBR)' },
    { name: 'textures', title: 'Textures' },
  ],
  fields: [
    defineField({
      name: 'slug',
      title: 'Slug technique',
      type: 'slug',
      group: 'main',
      description: 'Ex: placage-chene, laque-mat-noir, vernis-naturel — utilisé par le code.',
      options: { source: 'name', maxLength: 60 },
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'name',
      title: 'Nom (FR)',
      type: 'string',
      group: 'main',
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'nameAr',
      title: 'Nom (AR)',
      type: 'string',
      group: 'main',
    }),
    defineField({
      name: 'category',
      title: 'Catégorie',
      type: 'string',
      group: 'main',
      options: {
        list: [
          { title: 'Placage bois', value: 'wood' },
          { title: 'Laque', value: 'lacquer' },
          { title: 'Vernis naturel', value: 'natural' },
          { title: 'Métallique', value: 'metallic' },
          { title: 'Stratifié', value: 'laminate' },
        ],
      },
      validation: (R) => R.required(),
    }),
    defineField({
      name: 'baseColor',
      title: 'Couleur de base',
      type: 'string',
      group: 'pbr',
      description: 'Hex code, ex: #3D2817 (noyer foncé). Visible si pas de texture bois.',
      validation: (R) => R.regex(/^#[0-9a-fA-F]{6}$/).error('Format attendu : #RRGGBB'),
      initialValue: '#8B6F47',
    }),
    defineField({
      name: 'roughness',
      title: 'Rugosité (0 = miroir brillant, 1 = très mat)',
      type: 'number',
      group: 'pbr',
      description: 'Laqué brillant ≈ 0.08, laqué mat ≈ 0.55, placage bois ≈ 0.65',
      validation: (R) => R.min(0).max(1),
      initialValue: 0.55,
    }),
    defineField({
      name: 'metallic',
      title: 'Métallicité (0 = non-métal, 1 = métal pur)',
      type: 'number',
      group: 'pbr',
      description: 'Bois/laque = 0. Inox/alu brossé = 0.9.',
      validation: (R) => R.min(0).max(1),
      initialValue: 0,
    }),
    defineField({
      name: 'woodTexture',
      title: 'Texture bois (diffuse map)',
      type: 'image',
      group: 'textures',
      description: 'Image de veines de bois (carreau 2048×2048 idéal). Appliquée comme baseColorTexture sur le panneau.',
      options: { hotspot: false },
    }),
    defineField({
      name: 'normalMap',
      title: 'Normal map (relief de surface)',
      type: 'image',
      group: 'textures',
      description: 'Optionnel — image normal map pour relief 3D (veines en relief, grain).',
      options: { hotspot: false },
    }),
    defineField({
      name: 'swatch',
      title: 'Pastille catalogue',
      type: 'image',
      group: 'main',
      description: 'Petite image (200×120) utilisée comme pastille dans le sélecteur du configurateur.',
      options: { hotspot: false },
    }),
    defineField({
      name: 'order',
      title: "Ordre d'affichage",
      type: 'number',
      group: 'main',
      initialValue: 100,
    }),
    defineField({
      name: 'published',
      title: 'Publié',
      type: 'boolean',
      group: 'main',
      initialValue: true,
    }),
  ],
  preview: {
    select: { title: 'name', subtitle: 'category', media: 'swatch' },
  },
  orderings: [
    {
      title: 'Catégorie + ordre',
      name: 'catOrder',
      by: [
        { field: 'category', direction: 'asc' },
        { field: 'order', direction: 'asc' },
      ],
    },
  ],
});
